/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Mahasiswa;
import projectuaspbo.Database;

/**
 *
 * @author Dodi
 */
public class InfoKasKelasView extends javax.swing.JFrame {
    private static String nim;
    private DefaultTableModel tableModel;
    /**
     * Creates new form KasKelas
     * @param nim
     */
    public InfoKasKelasView(String nim) {
        this.nim = nim;
        initComponents();
        fillData(nim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kelasLable = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kasKelasTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        bukti = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        kas = new javax.swing.JLabel();
        cariTextField = new javax.swing.JTextField();
        cariButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        exportCsvButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(820, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 720));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7.png"))); // NOI18N

        kelasLable.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        kelasLable.setForeground(new java.awt.Color(51, 51, 51));
        kelasLable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kelasLable.setText("Kas Kelas");
        kelasLable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        backLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        backLabel.setForeground(new java.awt.Color(51, 51, 51));
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setText("Back");
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        kasKelasTable.setBackground(new java.awt.Color(255, 255, 255));
        kasKelasTable.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        kasKelasTable.setForeground(new java.awt.Color(51, 51, 51));
        kasKelasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Bulan Bayar", "Bukti Bayar", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(kasKelasTable);

        jScrollPane2.setViewportView(bukti);

        statusComboBox.setBackground(new java.awt.Color(255, 255, 255));
        statusComboBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        statusComboBox.setForeground(new java.awt.Color(0, 0, 0));
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Dikonfirmasi", "Konfirmasi" }));
        statusComboBox.setSelectedIndex(-1);
        statusComboBox.setSelectedItem(kasKelasTable.getSelectedRows());

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bukti Transfer");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        kas.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        kas.setForeground(new java.awt.Color(51, 51, 51));
        kas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kas.setText("Rp.");
        kas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cariTextField.setBackground(new java.awt.Color(255, 255, 255));
        cariTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cariTextField.setForeground(new java.awt.Color(51, 51, 51));

        cariButton.setBackground(new java.awt.Color(0, 51, 255));
        cariButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cariButton.setForeground(new java.awt.Color(255, 255, 255));
        cariButton.setText("Cari");
        cariButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        exportButton.setBackground(new java.awt.Color(0, 51, 255));
        exportButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        exportButton.setForeground(new java.awt.Color(255, 255, 255));
        exportButton.setText("Export XLSX");
        exportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        hapusButton.setBackground(new java.awt.Color(255, 51, 0));
        hapusButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusButton.setText("Hapus");
        hapusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah Kas ");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        exportCsvButton.setBackground(new java.awt.Color(0, 51, 255));
        exportCsvButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        exportCsvButton.setForeground(new java.awt.Color(255, 255, 255));
        exportCsvButton.setText("Export CSV");
        exportCsvButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kelasLable))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cariButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hapusButton)
                                        .addGap(54, 54, 54)
                                        .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(exportCsvButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exportButton)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backLabel)
                        .addGap(734, 734, 734))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(kelasLable)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariButton))
                        .addGap(8, 8, 8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapusButton))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kas)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exportCsvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JTable getKasKelasTable() {
        return kasKelasTable;
    }
    
    public String getCariNama() {
        return cariTextField.getText();
    }

    public void addCariButtonActionListener(ActionListener listener) {
        cariButton.addActionListener(listener);
    }
    
    public void addExportButtonActionListener(ActionListener listener) {
        exportButton.addActionListener(listener);
    }
    
    public void addExportCsvButtonActionListener(ActionListener listener) {
        exportCsvButton.addActionListener(listener);
    }
    
    public void updateTableDataSearch(List<Object[]> data) {
        if (tableModel == null) {
            tableModel = (DefaultTableModel) kasKelasTable.getModel();
        }
        tableModel.setRowCount(0);
        for (Object[] row : data) {
            tableModel.addRow(row);
        }
    }
    
    public void addTableMouseListener(MouseListener listener) {
        kasKelasTable.addMouseListener(listener);
    }
    
    public int getSelectedRow() {
        return kasKelasTable.getSelectedRow();
    }

    public String getNimAtRow(int row) {
        return kasKelasTable.getValueAt(row, 0).toString();
    }

    public String getBulanAtRow(int row) {
        return kasKelasTable.getValueAt(row, 2).toString();
    }
    
    public void setBuktiImageIcon(ImageIcon imageIcon) {
        bukti.setIcon(imageIcon);
    }

    public void setBuktiText(String text) {
        bukti.setText(text);
    }
    
    public String getSelectedStatus() {
        return (String) statusComboBox.getSelectedItem();
    }

    public void setSelectedStatus(String status) {
        statusComboBox.setSelectedItem(status);
    }

    public void addUpdateActionListener(ActionListener listener) {
        statusComboBox.addActionListener(listener);
    }
    
    public void addHapusActionListener(ActionListener listener) {
        hapusButton.addActionListener(listener);
    }
    
    public void setUangText(String text) {
        kas.setText(text);
    }
    
    public void setCariNama(String string) {
        cariTextField.setText("");
    }
    
    public void fillData(String nim) {
        try {
            Mahasiswa user = Database.getInstance().getUserByNim(nim);
            kelasLable.setText("INFORMASI KAS KELAS "+user.getKelas()); 
        } catch (SQLException ex) {
            Logger.getLogger(MenuMahasiswaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public String getNim(){
        return nim;
    }
    
    public void addBackMouseListener(MouseListener listener) {
        backLabel.addMouseListener(listener);
    }
    
    public void updateTableData(List<Object[]> data) {
        if (tableModel == null) {
            tableModel = (DefaultTableModel) kasKelasTable.getModel();
        }
        tableModel.setRowCount(0);
        for (Object[] row : data) {
            tableModel.addRow(row);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoKasKelasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoKasKelasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoKasKelasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoKasKelasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoKasKelasView(nim).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel bukti;
    private javax.swing.JButton cariButton;
    private javax.swing.JTextField cariTextField;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton exportCsvButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kas;
    private javax.swing.JTable kasKelasTable;
    private javax.swing.JLabel kelasLable;
    public javax.swing.JComboBox<String> statusComboBox;
    // End of variables declaration//GEN-END:variables

}
