/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Dodi
 */
public class KasAngkatanView extends javax.swing.JFrame {
    private static String nim;
    /**
     * Creates new form BayarKasKelas
     * @param nim
     */
    public KasAngkatanView(String nim) {
        this.nim = nim;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        uang = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        backLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        januariCheckBox = new javax.swing.JCheckBox();
        februariCheckBox = new javax.swing.JCheckBox();
        maretCheckBox = new javax.swing.JCheckBox();
        aprilCheckBox = new javax.swing.JCheckBox();
        meiCheckBox = new javax.swing.JCheckBox();
        juniCheckBox = new javax.swing.JCheckBox();
        juliCheckBox = new javax.swing.JCheckBox();
        agustusCheckBox = new javax.swing.JCheckBox();
        septemberCheckBox = new javax.swing.JCheckBox();
        oktoberCheckBox = new javax.swing.JCheckBox();
        novemberCheckBox = new javax.swing.JCheckBox();
        desemberCheckBox = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        openFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(527, 644));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PEMBAYARAN KAS ANGKATAN");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Yang Harus Dibayar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pilih Bulan Yang Ingin Dibayar");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        uang.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        uang.setForeground(new java.awt.Color(51, 51, 51));
        uang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uang.setText("Rp");
        uang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Upload Bukti Pembayaran");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        submitButton.setBackground(new java.awt.Color(0, 51, 255));
        submitButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setAlignmentY(0.0F);
        submitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.setMargin(new java.awt.Insets(3, 14, 3, 14));

        backLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        backLabel.setForeground(new java.awt.Color(51, 51, 51));
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setText("Back");
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N

        januariCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        januariCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        januariCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        januariCheckBox.setText("Januari");

        februariCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        februariCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        februariCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        februariCheckBox.setText("Februari");

        maretCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        maretCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        maretCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        maretCheckBox.setText("Maret");

        aprilCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        aprilCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        aprilCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        aprilCheckBox.setText("April");

        meiCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        meiCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        meiCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        meiCheckBox.setText("Mei");

        juniCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        juniCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        juniCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        juniCheckBox.setText("Juni");

        juliCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        juliCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        juliCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        juliCheckBox.setText("Juli");

        agustusCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        agustusCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        agustusCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        agustusCheckBox.setText("Agustus");

        septemberCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        septemberCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        septemberCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        septemberCheckBox.setText("September");

        oktoberCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        oktoberCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        oktoberCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        oktoberCheckBox.setText("Oktober");

        novemberCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        novemberCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        novemberCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        novemberCheckBox.setText("November");

        desemberCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        desemberCheckBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        desemberCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        desemberCheckBox.setText("Desember");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));

        openFileButton.setBackground(new java.awt.Color(51, 51, 255));
        openFileButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        openFileButton.setForeground(new java.awt.Color(255, 255, 255));
        openFileButton.setText("Open File");
        openFileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(uang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(backLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(januariCheckBox)
                            .addComponent(aprilCheckBox))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(februariCheckBox)
                            .addComponent(meiCheckBox)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(juliCheckBox)
                            .addComponent(oktoberCheckBox))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(novemberCheckBox)
                            .addComponent(agustusCheckBox))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desemberCheckBox)
                    .addComponent(juniCheckBox)
                    .addComponent(maretCheckBox)
                    .addComponent(septemberCheckBox))
                .addGap(102, 102, 102))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openFileButton))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(januariCheckBox)
                    .addComponent(februariCheckBox)
                    .addComponent(maretCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aprilCheckBox)
                    .addComponent(meiCheckBox)
                    .addComponent(juniCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juliCheckBox)
                    .addComponent(agustusCheckBox)
                    .addComponent(septemberCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oktoberCheckBox)
                    .addComponent(novemberCheckBox)
                    .addComponent(desemberCheckBox))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(openFileButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backLabel)))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void addCheckboxActionListener(ActionListener listener) {
        januariCheckBox.addActionListener(listener);
        februariCheckBox.addActionListener(listener);
        maretCheckBox.addActionListener(listener);
        aprilCheckBox.addActionListener(listener);
        meiCheckBox.addActionListener(listener);
        juniCheckBox.addActionListener(listener);
        juliCheckBox.addActionListener(listener);
        agustusCheckBox.addActionListener(listener);
        septemberCheckBox.addActionListener(listener);
        oktoberCheckBox.addActionListener(listener);
        novemberCheckBox.addActionListener(listener);
        desemberCheckBox.addActionListener(listener);
    }

    public void addOpenFileActionListener(ActionListener listener) {
        openFileButton.addActionListener(listener);
    }

    public void addSubmitActionListener(ActionListener listener) {
        submitButton.addActionListener(listener);
    }

    public void addBackMouseListener(MouseListener listener) {
        backLabel.addMouseListener(listener);
    }

    public boolean isJanuariSelected() {
        return januariCheckBox.isSelected();
    }

    public boolean isFebruariSelected() {
        return februariCheckBox.isSelected();
    }

    public boolean isMaretSelected() {
        return maretCheckBox.isSelected();
    }

    public boolean isAprilSelected() {
        return aprilCheckBox.isSelected();
    }

    public boolean isMeiSelected() {
        return meiCheckBox.isSelected();
    }

    public boolean isJuniSelected() {
        return juniCheckBox.isSelected();
    }

    public boolean isJuliSelected() {
        return juliCheckBox.isSelected();
    }

    public boolean isAgustusSelected() {
        return agustusCheckBox.isSelected();
    }

    public boolean isSeptemberSelected() {
        return septemberCheckBox.isSelected();
    }

    public boolean isOktoberSelected() {
        return oktoberCheckBox.isSelected();
    }

    public boolean isNovemberSelected() {
        return novemberCheckBox.isSelected();
    }

    public boolean isDesemberSelected() {
        return desemberCheckBox.isSelected();
    }

    public void setTotalAmount(int total) {
        uang.setText("Rp."+String.valueOf(total));
    }

    public int getTotalAmount() {
        return Integer.parseInt(uang.getText());
    }

    public void setFilePath(String filePath) {
        jTextField1.setText(filePath);
    }

    public String getFilePath() {
        return jTextField1.getText();
    }
    
    public String getNim(){
        return nim;
    }

    public void setJanuariEnabled(boolean enabled) {
        januariCheckBox.setEnabled(enabled);
    }

    public void setFebruariEnabled(boolean enabled) {
        februariCheckBox.setEnabled(enabled);
    }

    public void setMaretEnabled(boolean enabled) {
        maretCheckBox.setEnabled(enabled);
    }

    public void setAprilEnabled(boolean enabled) {
        aprilCheckBox.setEnabled(enabled);
    }

    public void setMeiEnabled(boolean enabled) {
        meiCheckBox.setEnabled(enabled);
    }

    public void setJuniEnabled(boolean enabled) {
        juniCheckBox.setEnabled(enabled);
    }

    public void setJuliEnabled(boolean enabled) {
        juliCheckBox.setEnabled(enabled);
    }

    public void setAgustusEnabled(boolean enabled) {
        agustusCheckBox.setEnabled(enabled);
    }

    public void setSeptemberEnabled(boolean enabled) {
        septemberCheckBox.setEnabled(enabled);
    }

    public void setOktoberEnabled(boolean enabled) {
        oktoberCheckBox.setEnabled(enabled);
    }

    public void setNovemberEnabled(boolean enabled) {
        novemberCheckBox.setEnabled(enabled);
    }

    public void setDesemberEnabled(boolean enabled) {
        desemberCheckBox.setEnabled(enabled);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasAngkatanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasAngkatanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasAngkatanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasAngkatanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasAngkatanView(nim).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agustusCheckBox;
    private javax.swing.JCheckBox aprilCheckBox;
    private javax.swing.JLabel backLabel;
    private javax.swing.JCheckBox desemberCheckBox;
    private javax.swing.JCheckBox februariCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox januariCheckBox;
    private javax.swing.JCheckBox juliCheckBox;
    private javax.swing.JCheckBox juniCheckBox;
    private javax.swing.JCheckBox maretCheckBox;
    private javax.swing.JCheckBox meiCheckBox;
    private javax.swing.JCheckBox novemberCheckBox;
    private javax.swing.JCheckBox oktoberCheckBox;
    private javax.swing.JButton openFileButton;
    private javax.swing.JCheckBox septemberCheckBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel uang;
    // End of variables declaration//GEN-END:variables
}
