/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dodi
 */
public class RiwayatBayarView extends javax.swing.JFrame {
    private static String nim;
    private DefaultTableModel tableModel;
    private DefaultTableModel tableModel2;
    /**
     * Creates new form RiwayatBayar
     * @param nim
     */
    public RiwayatBayarView(String nim) {
        this.nim = nim;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kasKelasTable = new javax.swing.JTable();
        kasKelas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kasAngkatanTable = new javax.swing.JTable();
        kasKelas1 = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(627, 720));
        setMinimumSize(new java.awt.Dimension(627, 720));
        setPreferredSize(new java.awt.Dimension(627, 730));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(627, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(627, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(627, 720));

        jLabel2.setBackground(new java.awt.Color(102, 51, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RIWAYAT PEMBAYARAN KAS");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        kasKelasTable.setBackground(new java.awt.Color(255, 255, 255));
        kasKelasTable.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        kasKelasTable.setForeground(new java.awt.Color(51, 51, 51));
        kasKelasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Kelas", "Bulan Bayar", "Status Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(kasKelasTable);

        kasKelas.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        kasKelas.setForeground(new java.awt.Color(51, 51, 51));
        kasKelas.setText("Pembayaran Kas Kelas");
        kasKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        kasAngkatanTable.setBackground(new java.awt.Color(255, 255, 255));
        kasAngkatanTable.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        kasAngkatanTable.setForeground(new java.awt.Color(51, 51, 51));
        kasAngkatanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Kelas", "Bulan Bayar", "Status Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(kasAngkatanTable);

        kasKelas1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        kasKelas1.setForeground(new java.awt.Color(51, 51, 51));
        kasKelas1.setText("Pembayaran Kas Angkatan");
        kasKelas1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        backLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        backLabel.setForeground(new java.awt.Color(51, 51, 51));
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setText("Back");
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backLabel)
                    .addComponent(kasKelas1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kasKelas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(kasKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(kasKelas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(backLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void addBackMouseListener(MouseListener listener) {
        backLabel.addMouseListener(listener);
    }
    
    public void updateTableData(List<Object[]> data) {
        if (tableModel == null) {
            tableModel = (DefaultTableModel) kasKelasTable.getModel();
        }
        tableModel.setRowCount(0);
        for (Object[] row : data) {
            tableModel.addRow(row);
        }
    }
    
    public void updateTableDataAngkatan(List<Object[]> data) {
        if (tableModel2 == null) {
            tableModel2 = (DefaultTableModel) kasAngkatanTable.getModel();
        }
        tableModel2.setRowCount(0);
        for (Object[] row : data) {
            tableModel2.addRow(row);
        }
    }
    
    public String getNim(){
        return nim;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatBayarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatBayarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatBayarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatBayarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable kasAngkatanTable;
    private javax.swing.JLabel kasKelas;
    private javax.swing.JLabel kasKelas1;
    public javax.swing.JTable kasKelasTable;
    // End of variables declaration//GEN-END:variables
}